### ISSUE TITLE
Prefix ENUM's with NW_

### ISSUE THREAD

**Issue by mrcodetastic** [ayushsharma82/NetWizard#11]
Hello,

Great library. I want to use this library with some other libraries and I'm getting a conflict with the ENUM labels that have been defined. Perhaps you can change it so all ENUM labels (like 'TIMEOUT') have a NW_ prefix to avoid conflicts.

Conflict with ezTime library. I'll be hacking this one for the moment.

```
In file included from src/main.cpp:10:
.pio/libdeps/esp32dev/NetWizard/src/NetWizard.h:111:3: error: 'TIMEOUT' conflicts with a previous declaration
  111 |   TIMEOUT
      |   ^~~~~~~
In file included from lib/clockfaces/../cw-commons/CWDateTime.h:4,
                 from lib/clockfaces/../cw-commons/IClockface.h:3,
                 from lib/clockfaces/Clockfaces.hpp:9,
                 from src/main.cpp:6:
.pio/libdeps/esp32dev/ezTime/src/ezTime.h:57:9: note: previous declaration 'ezError_t TIMEOUT'
   57 |         TIMEOUT,```

**Comment by ayushsharma82** [comment]
@mrcodetastic ~~I've added the fix in `dev` branch. You can test it out in your code and let me know: https://github.com/ayushsharma82/NetWizard/tree/dev~~

Everything was working fine so fix is in v1.1.0 release. You can test it out and let me know if you encounter any issue.

**Comment by mrcodetastic** [comment]
Works perfectly.  This is an excellent library.

**Comment by mrcodetastic** [comment]
Also, if you have a paypal etc. Let me know as I don't need to buy a pro / commercial version but would be happy to contribute for efforts.

**Comment by ayushsharma82** [comment]
It’s ok. 😄 I’m glad you like the library; seeing people use these libraries is more than enough.

Also, libraries are under my company so everything is paid for. The lite & pro offering ensures that some budget is allocated for maintenance of open source editions whenever someone buys a pro library - this helps everything stay afloat.
