### ISSUE TITLE
Request body not found.

### ISSUE THREAD

**Issue by msanaullahsahar** [ayushsharma82/NetWizard#13]
NetWizard library ---> default example: Async Demo. The example compiled and uploaded to esp32 dev kit successfully. ESP32 acts as APN. Other devices can connect to it. I can choose SSID and can enter password, after that the MQTT page/screen comes in. On entering mqtt broker and hitting FINISH button, an error appears on the top suggesting, **Request body not found.**
![git](https://github.com/user-attachments/assets/c45618a4-219a-434f-86ed-a1272e1a27db)

**Comment by ayushsharma82** [comment]
@msanaullahsahar  Can you verify which version of NetWizard are you using? This bug was fixed with v1.0.9 release.

**Comment by msanaullahsahar** [comment]
Its 1.0.8 and installed through Arduino IDE library manager.

**Comment by ayushsharma82** [comment]
Okay. The issue will be resolved upon updating to the latest version.
