### ISSUE TITLE
onConfig Callback Getters not returning entered Value.

### ISSUE THREAD

**Issue by liampclark** [ayushsharma82/NetWizard#15]
onConfig Callback Getters not returning entered values Value.

![image](https://github.com/user-attachments/assets/5ab1c19b-b7a6-4dbe-80f3-2f6dc21e3e17)

using AsyncDemo & NetWizardPro-v1-0-2

**Comment by ayushsharma82** [comment]
Hi @liampclark , Thanks for the bug report. I'll take a look at it.

**Comment by ayushsharma82** [comment]
I am pleased to announce that I have released version 1.0.4 of NetWizardPro, which resolves the issue you reported.
